### ISSUE TITLE
Image wrong file size after upload

### ISSUE THREAD

**Issue by dircm** [TaffoVelikoff/imagekit-adapter#1]
Hi Taffo, I am trying to upload a JPG image to imagekit.

I first get the file from local storage :

`$image = Storage::disk('local')->get('test.jpg');
`

This is a 311kb jpg file.

Then put it to the imagekit disk:

`Storage::disk('imagekit')->put('test2.jpg', $image);`

But the image is not rendering and the file size is only 113 bytes.

Can you help me understand what I am doing wrong?  Thanks Tom.

**Comment by sinnbeck** [comment]
Did you turn off all optimizations and try again?

https://imagekit.io/dashboard#settings-optimization

**Comment by TaffoVelikoff** [comment]
Hi!
Sorry, I forgot to mention something in the documentations. You should either use a url or encode the image as base64.
This works for me:

$image = Storage::disk('local')->get('test.jpg'); 
Storage::disk('imagekit')->put('test2.jpg', base64_encode($image));

or you can do this:
Storage::disk('imagekit')->put('test2.jpg', 'https://mydomian.com/path/to/image');

You can see more here: https://docs.imagekit.io/api-reference/upload-file-api/server-side-file-upload

I hope this helps. Thank you for contributing!

**Comment by dircm** [comment]
That worked, thanks @TaffoVelikoff !  I forgot to mention that the API call using the imageklit library also showed the same issue.

`Storage::disk('imagekit')->put('test2.jpg', base64_encode($image));`
